### ISSUE TITLE
Friend, could you update the dlib-19.24.2-cp311-cp311-win-amd64.whl?

### ISSUE THREAD

**Issue by NPOSUI** [Murtaza-Saeed/dlib#2]
thx!

**Comment by NPOSUI** [comment]
I installed "dlib-19.24.1-cp311-cp311-win-amd64.whl" failed in my local terminal. 
Error info: "ERROR: Wheel 'dlib' located at C:\Tmp\dlib-19.24.1-cp311-cp311-win_amd64.whl is invalid."
And my Python version is 3.11.4. So have you met this error?

**Comment by Murtaza-Saeed** [comment]
Dnt worry, follow and message 👇
https://www.instagram.com/murtazasaeed/

**Comment by NPOSUI** [comment]
Thanks for your reply. I use conda installed dlib. 
`conda install -c conda-forge dlib`

**Comment by chwshuang** [comment]
download:https://github.com/z-mahmud22/Dlib_Windows_Python3.x
